title: Selected Areas in Cryptography (SAC) 2023
description: SAC is Canada's research conference on cryptography, held annually since 1994. The 30th edition of SAC will take place at the University of New Brunswick in New Brunswick, Canada from August 16-18, 2023, and will be preceded by the SAC Summer School on August 14 and 15, 2023.
