title: Selected Areas in Cryptography (SAC) 2019
description: SAC is Canada's research conference on cryptography, held annually since 1994. The 26th edition of SAC will take place at the University of Waterloo in Ontario, Canada from August 14-16, 2019, and will be preceded by the SAC Summer School on August 12 and 13, 2019.
