name: Deploy to sacworkshop.org

on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: sacworkshop.org
    steps:
    - uses: actions/checkout@v3
    - name: Build the site using Jekyll in a container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Set up SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > github-sac-dsa
        chmod 600 github-sac-dsa
        chmod 700 .
    - name: Set up SSH known hosts
      run: |
        echo "${{ vars.SSH_HOST_FINGERPRINT }}" > known_hosts
        chmod 600 known_hosts
    - name: Copy to sacworkshop.org using scp
      run: |
        scp \
          -i github-sac-dsa \
          -oHostKeyAlgorithms=ssh-dss \
          -oPubkeyAcceptedAlgorithms=ssh-dss \
          -oUserKnownHostsFile=known_hosts \
          -O \
          -C \
          -r \
          ${{ github.workspace }}/_site/* \
          fimtfj2j0n6m@sacworkshop.org:public_html/SAC23
